url: https://sanduni-p.github.io/IntroPython-Bio/
project:
  type: website

website:
  title: "Introduction to Python"
  navbar:
    left:
      - href: index.html
        text: Home
      - text: Workshop Materials
        menu: 
          - text: Getting Started with Jupyter Notebook
            href: vignettes/1_Introduction.qmd
          - text: Python Fundamentals
            href: vignettes/2_Intro_Python.qmd
          - text: Loading and Viewing Patient Data
            href: vignettes/3_Loading_Data.qmd
          - text: Analysing Patient Data
            href: vignettes/4_Analysing_Data.qmd
          - text: Visualising Patient Data
            href: vignettes/5_Visualising_Data.qmd

format:
  html:
    theme: 
      - cerulean
      - utils/css/custom.scss
    toc: true
    toc-expand: 1
    toc-title: Contents
    embed-resources: true
    css: utils/css/custom.css
    smooth-scroll: true
    code-copy: hover
    df-print: kable

execute:
  cache: false
